#!/bin/bash
################################################################################
# Generate strings_license.xml from ANYLINE_MOBILE_SDK_LICENSE_KEY env variable
################################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/../app/src/main/res/values/strings_license.xml"

if [ -z "$ANYLINE_MOBILE_SDK_LICENSE_KEY" ]; then
    echo "Error: ANYLINE_MOBILE_SDK_LICENSE_KEY environment variable is not set"
    echo ""
    echo "Please set it in your shell profile (~/.zshrc or ~/.bashrc):"
    echo "  export ANYLINE_MOBILE_SDK_LICENSE_KEY='your-license-key-here'"
    echo ""
    echo "Then reload your shell or run: source ~/.zshrc"
    exit 1
fi

# Create the license file
cat > "$OUTPUT_FILE" << EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by generate_license_key.sh - DO NOT COMMIT TO PUBLIC REPOS -->
<resources>
    <string name="anyline_license_key" translatable="false">$ANYLINE_MOBILE_SDK_LICENSE_KEY</string>
</resources>
EOF

echo "Generated $OUTPUT_FILE with license key"
